name: Generate GitHub Contribution Snake

on:
  push:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate contribution snake
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            profile/snake.svg

      # Commit generated snake
      - name: Commit Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "profile/snake.svg"
          message: "Update contribution snake"
